### ISSUE TITLE
不能使用插件

### ISSUE THREAD

**Issue by houzhaoshijiazu** [mrmanzhaow/RestfulToolkit#15]
一使用idea报空指针

**Comment by xiaosunzhu** [comment]
null
java.lang.NullPointerException
	at com.zhaow.restful.common.PsiAnnotationHelper.getAnnotationAttributeValues(PsiAnnotationHelper.java:54)
	at com.zhaow.restful.common.spring.RequestMappingAnnotationHelper.getRequestMappings(RequestMappingAnnotationHelper.java:96)
	at com.zhaow.restful.common.spring.RequestMappingAnnotationHelper.getRequestPaths(RequestMappingAnnotationHelper.java:40)
	at com.zhaow.restful.common.resolver.SpringResolver.getServiceItemList(SpringResolver.java:178)
	at com.zhaow.restful.common.resolver.SpringResolver.getRestServiceItemList(SpringResolver.java:137)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.findAllSupportedServiceItemsInModule(BaseServiceResolver.java:38)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceItemListUsingResolver(ServiceHelper.java:55)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceProjectListUsingResolver(ServiceHelper.java:36)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.lambda$getServiceProjects$0(RestServiceProjectsManager.java:68)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:79)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:110)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:79)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.getServiceProjects(RestServiceProjectsManager.java:68)
	at com.zhaow.restful.navigator.RestServiceStructure.update(RestServiceStructure.java:99)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureUpdate$1(RestServicesNavigator.java:157)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureRequest$2(RestServicesNavigator.java:174)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:430)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Troy-An** [comment]
同上 空指针错误
java.lang.NullPointerException
at com.zhaow.restful.common.PsiAnnotationHelper.getAnnotationAttributeValues(PsiAnnotationHelper.java:54)
