### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by yhan219** [mrmanzhaow/RestfulToolkit#2]
- kotlin项目中，copy full url 时spring boot yml配置文件中的context-path无效
- 不知道为什么我的项目只要有kotlin代码，url树就一直显示不出来，而且不能根据url搜索。我的idea版本是2018.1，kotlin：1.2.31。有时候会报错：
``` java
No enum constant com.zhaow.restful.method.HttpMethod.HEAD
java.lang.IllegalArgumentException: No enum constant com.zhaow.restful.method.HttpMethod.HEAD
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.zhaow.restful.method.HttpMethod.valueOf(HttpMethod.java:6)
	at com.zhaow.restful.method.HttpMethod.getByRequestMethod(HttpMethod.java:21)
	at com.zhaow.restful.navigation.action.RestServiceItem.<init>(RestServiceItem.java:45)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.createRestServiceItem(BaseServiceResolver.java:85)
	at com.zhaow.restful.common.resolver.SpringResolver.getServiceItemList(SpringResolver.java:167)
	at com.zhaow.restful.common.resolver.SpringResolver.getRestServiceItemList(SpringResolver.java:141)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.findAllSupportedServiceItemsInModule(BaseServiceResolver.java:40)
	at com.zhaow.restful.common.resolver.SpringResolver.findAllSupportedServiceItemsInModule(SpringResolver.java:179)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceItemListUsingResolver(ServiceHelper.java:58)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceProjectListUsingResolver(ServiceHelper.java:40)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.lambda$getServiceProjects$0(RestServiceProjectsManager.java:68)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:79)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:110)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:79)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.getServiceProjects(RestServiceProjectsManager.java:68)
	at com.zhaow.restful.navigator.RestServiceStructure.update(RestServiceStructure.java:98)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureUpdate$1(RestServicesNavigator.java:157)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureRequest$2(RestServicesNavigator.java:174)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:430)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.IllegalArgumentException: No enum constant com.zhaow.restful.method.HttpMethod.HEAD
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.zhaow.restful.method.HttpMethod.valueOf(HttpMethod.java:6)
	at com.zhaow.restful.method.HttpMethod.getByRequestMethod(HttpMethod.java:21)
	at com.zhaow.restful.navigation.action.RestServiceItem.<init>(RestServiceItem.java:45)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.createRestServiceItem(BaseServiceResolver.java:85)
	at com.zhaow.restful.common.resolver.SpringResolver.getServiceItemList(SpringResolver.java:167)
	at com.zhaow.restful.common.resolver.SpringResolver.getRestServiceItemList(SpringResolver.java:141)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.findAllSupportedServiceItemsInModule(BaseServiceResolver.java:40)
	at com.zhaow.restful.common.resolver.SpringResolver.findAllSupportedServiceItemsInModule(SpringResolver.java:179)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceItemListUsingResolver(ServiceHelper.java:58)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceProjectListUsingResolver(ServiceHelper.java:40)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.lambda$getServiceProjects$0(RestServiceProjectsManager.java:68)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:79)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:110)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:79)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.getServiceProjects(RestServiceProjectsManager.java:68)
	at com.zhaow.restful.navigator.RestServiceStructure.update(RestServiceStructure.java:98)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureUpdate$1(RestServicesNavigator.java:157)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureRequest$2(RestServicesNavigator.java:174)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:430)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.IllegalArgumentException: No enum constant com.zhaow.restful.method.HttpMethod.HEAD
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.zhaow.restful.method.HttpMethod.valueOf(HttpMethod.java:6)
	at com.zhaow.restful.method.HttpMethod.getByRequestMethod(HttpMethod.java:21)
	at com.zhaow.restful.navigation.action.RestServiceItem.<init>(RestServiceItem.java:45)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.createRestServiceItem(BaseServiceResolver.java:85)
	at com.zhaow.restful.common.resolver.SpringResolver.getServiceItemList(SpringResolver.java:167)
	at com.zhaow.restful.common.resolver.SpringResolver.getRestServiceItemList(SpringResolver.java:141)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.findAllSupportedServiceItemsInModule(BaseServiceResolver.java:40)
	at com.zhaow.restful.common.resolver.SpringResolver.findAllSupportedServiceItemsInModule(SpringResolver.java:179)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceItemListUsingResolver(ServiceHelper.java:58)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceProjectListUsingResolver(ServiceHelper.java:40)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.lambda$getServiceProjects$0(RestServiceProjectsManager.java:68)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:79)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:110)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:79)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.getServiceProjects(RestServiceProjectsManager.java:68)
	at com.zhaow.restful.navigator.RestServiceStructure.update(RestServiceStructure.java:98)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureUpdate$1(RestServicesNavigator.java:157)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureRequest$2(RestServicesNavigator.java:174)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:430)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



```

还有这个错：

``` java
null
java.lang.NullPointerException
	at com.zhaow.restful.common.spring.RequestMappingAnnotationHelper.getRequestPaths(RequestMappingAnnotationHelper.java:144)
	at com.zhaow.restful.common.resolver.SpringResolver.getServiceItemList(SpringResolver.java:160)
	at com.zhaow.restful.common.resolver.SpringResolver.tryFindKtRestServiceItems(SpringResolver.java:214)
	at com.zhaow.restful.common.resolver.SpringResolver.findAllSupportedServiceItemsInModule(SpringResolver.java:181)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceItemListUsingResolver(ServiceHelper.java:58)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceProjectListUsingResolver(ServiceHelper.java:40)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.lambda$getServiceProjects$0(RestServiceProjectsManager.java:68)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:79)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:110)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:79)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.getServiceProjects(RestServiceProjectsManager.java:68)
	at com.zhaow.restful.navigator.RestServiceStructure.update(RestServiceStructure.java:98)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureUpdate$1(RestServicesNavigator.java:157)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureRequest$2(RestServicesNavigator.java:174)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:430)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mrmanzhaow** [comment]
谢谢你的反馈，近期会更新 2.0.4 版本，这两个问题已经解决。
