### ISSUE TITLE
引入的多项目，不仅仅有web服务，还有service等，就不好使了，只有一个web服务时候好使

### ISSUE THREAD

**Issue by RainElohim** [mrmanzhaow/RestfulToolkit#21]
java.lang.NullPointerException
	at com.zhaow.restful.common.PsiAnnotationHelper.getAnnotationAttributeValues(PsiAnnotationHelper.java:54)
	at com.zhaow.restful.common.rose.RoseAnnotationHelper.getRequestPaths(RoseAnnotationHelper.java:66)
	at com.zhaow.restful.common.rose.RoseAnnotationHelper.getRequestPathList(RoseAnnotationHelper.java:46)
	at com.zhaow.restful.common.rose.RoseAnnotationHelper.getRequestPaths(RoseAnnotationHelper.java:27)
	at com.zhaow.restful.common.resolver.RoseResolver.getRestServiceItemList(RoseResolver.java:65)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.findAllSupportedServiceItemsInModule(BaseServiceResolver.java:38)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceItemListUsingResolver(ServiceHelper.java:55)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceProjectListUsingResolver(ServiceHelper.java:36)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.lambda$getServiceProjects$0(RestServiceProjectsManager.java:68)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:108)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:140)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:108)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.getServiceProjects(RestServiceProjectsManager.java:68)
	at com.zhaow.restful.navigator.RestServiceStructure.update(RestServiceStructure.java:99)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureUpdate$1(RestServicesNavigator.java:157)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureRequest$2(RestServicesNavigator.java:174)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:453)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:405)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:404)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by RainElohim** [comment]
是不是可以通过自定义设置扫描路径解决呢？

**Comment by RainElohim** [comment]
注解里url用常量写的也识别不了
