### ISSUE TITLE
IDEA 2020.1 版本报异常

### ISSUE THREAD

**Issue by SnrtIevg** [mrmanzhaow/RestfulToolkit#31]
java.lang.NoClassDefFoundError: Could not initialize class com.zhaow.restful.common.ToolkitIcons
	at com.zhaow.restful.navigator.RestServicesNavigator.initToolWindow(RestServicesNavigator.java:118)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$initComponent$0(RestServicesNavigator.java:105)
	at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:86)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:458)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.lambda$run$0(StartupManagerImpl.java:349)
	at com.intellij.openapi.project.DumbServiceImpl.unsafeRunWhenSmart(DumbServiceImpl.java:283)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runDumbUnawareActivity$10(StartupManagerImpl.java:515)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:284)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runDumbUnawareActivity(StartupManagerImpl.java:514)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$200(StartupManagerImpl.java:48)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:349)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:434)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:426)
	at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:905)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by SnrtIevg** [comment]
但是基本不影响使用

**Comment by XueYat** [comment]
> 但是基本不影响使用

老哥，我这边不行呀，也是一样的错误，IDEA版本2020.1，点开RestServices里面就是空的  : (

**Comment by SnrtIevg** [comment]
> > 但是基本不影响使用
> 
> 老哥，我这边不行呀，也是一样的错误，IDEA版本2020.1，点开RestServices里面就是空的 : (

额，我是说搜索的功能， 另外的我很少用

**Comment by dream0708** [comment]
同样的问题

**Comment by wupuyuan** [comment]
一样的问题

**Comment by SnrtIevg** [comment]
有一个PR， 基于那位贡献者的代码构建的plugin 好像是没有问题的

**Comment by ghost** [comment]
一样的报错，点开右边菜单,一片空白哎...回退插件版本也没效果，IDEA版本2020.1.2

**Comment by SnrtIevg** [comment]
RestfulTool 这个插件功能一样， 我试过没什么问题
![image](https://user-images.githubusercontent.com/28601317/82792920-b2361200-9ea2-11ea-8313-b3780cf78a2a.png)
![image](https://user-images.githubusercontent.com/28601317/82792977-cd088680-9ea2-11ea-9788-524a4a91cc67.png)
原谅我的马赛克，哈哈
[restfultool 插件介绍](https://plugins.jetbrains.com/plugin/14280-restfultool)

**Comment by aborn** [comment]
看起来这个作者很久没维护了（2年），重新fork了一份，修复了这个bug，见：https://github.com/aborn/RestfulToolkit
下载地址见：https://github.com/aborn/RestfulToolkit/releases
2020.1可以下载https://github.com/aborn/RestfulToolkit/releases/download/3.0.0/WebDT-3.0.0_2020.1IU.zip 这个包，然后本地安装一下就可以。

**Comment by dayu007** [comment]
> 看起来这个作者很久没维护了（2年），重新fork了一份，修复了这个bug，见：https://github.com/aborn/RestfulToolkit
> 下载地址见：https://github.com/aborn/RestfulToolkit/releases
> 2020.1可以下载https://github.com/aborn/RestfulToolkit/releases/download/3.0.0/WebDT-3.0.0_2020.1IU.zip 这个包，然后本地安装一下就可以。

这文件无法安装，大兄弟！

**Comment by hangzhouljp** [comment]
暂时自己修改一下 但是把header头丢弃了 这个是打好的插件jar包 先对付一阵吧 https://github.com/hangzhouljp/lijinping
![image](https://user-images.githubusercontent.com/38392441/87007197-73f77680-c1f4-11ea-9f67-b8cd914b1287.png)
 再加载clone下来的那个jar包

**Comment by aborn** [comment]
> > 看起来这个作者很久没维护了（2年），重新fork了一份，修复了这个bug，见：https://github.com/aborn/RestfulToolkit
> > 下载地址见：https://github.com/aborn/RestfulToolkit/releases
> > 2020.1可以下载https://github.com/aborn/RestfulToolkit/releases/download/3.0.0/WebDT-3.0.0_2020.1IU.zip 这个包，然后本地安装一下就可以。
> 
> 这文件无法安装，大兄弟！

@dayu007 报什么错？

**Comment by chana1024** [comment]
@aborn  兄弟，2020.2无法安装。报不兼容。怎么处理
